services:
  - type: web
    name: fullstack_project1
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd project && gunicorn project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: PYTHON_VERSION
        value: 3.13.4
